language: rust

rust:
    - stable
    - nightly

services:
  - docker

cache: cargo

before_script:
    - rustup component add rustfmt

script:
- cargo build --verbose
- cargo test --verbose
- cargo fmt --all -- --check

matrix:
  allow_failures:
      - rust: nightly
  include:
      - name: Docker
        language: rust
        rust: stable
        script:
            - docker build .
