language: rust

rust:
    - stable
    - nightly

services:
  - docker

cache: cargo

before_script:
    - rustup component add rustfmt

script:
- cargo build --verbose
- cargo test --verbose
- cargo fmt --all -- --check
- docker build .

matrix:
  allow_failures:
    - rust: nightly
